#!/usr/bin/env python
"""Generate docs/coverage_matrix.md from the labelled manifest joined to the
REAL pytest --junitxml outcomes for tests/test_detectors.py.

The verdict column is the actual pytest result — never a hand-run. Regenerate
after changing the manifest or the detector tests:

    ./.venv/bin/python tools/coverage_matrix.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tests" / "oracle" / "manifest.yaml"
MATRIX = ROOT / "docs" / "coverage_matrix.md"
DETECTOR_TESTS = "tests/test_detectors.py"


def _pytest_outcomes() -> dict[str, bool]:
    """Run the detector tests and return {test_function_name: passed}."""
    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as handle:
        report = handle.name
    subprocess.run(
        [sys.executable, "-m", "pytest", DETECTOR_TESTS, "-q", "--junitxml", report],
        cwd=ROOT,
        check=False,
        capture_output=True,
    )
    tree = ET.parse(report)
    outcomes: dict[str, bool] = {}
    for testcase in tree.iter("testcase"):
        name = testcase.get("name", "")
        failed = any(child.tag in ("failure", "error", "skipped") for child in testcase)
        outcomes[name] = not failed
    return outcomes


def _fn(proving_test: str) -> str:
    return proving_test.split("::")[-1]


def build() -> str:
    cases: list[dict[str, Any]] = yaml.safe_load(MANIFEST.read_text())["cases"]
    outcomes = _pytest_outcomes()
    lines = [
        "# Coverage Matrix — discrimination evidence (L3)",
        "",
        "Generated by `tools/coverage_matrix.py` from the labelled manifest",
        "(`tests/oracle/manifest.yaml`) joined to **actual `pytest --junitxml`",
        "outcomes** for `tests/test_detectors.py`. The verdict column is the real",
        "pytest result — not a hand-run. This is discrimination evidence on the",
        "project's own labelled corpus (distinct from the Checkov/TerraGoat oracle).",
        "",
        "| rule_id | case | kind | fixture | proving test | expect | verdict |",
        "|---------|------|------|---------|--------------|--------|---------|",
    ]
    for case in cases:
        fn = _fn(case["proving_test"])
        passed = outcomes.get(fn)
        if passed is None:
            verdict = "MISSING (test not in run)"
        elif passed:
            verdict = f"PASS ({case['expect']})"
        else:
            verdict = "FAIL"
        lines.append(
            f"| {case['rule_id']} | {case['note']} | {case['kind']} | "
            f"`{Path(case['fixture']).name}` | `{fn}` | {case['expect']} | {verdict} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    MATRIX.parent.mkdir(parents=True, exist_ok=True)
    MATRIX.write_text(build())
    print(f"wrote {MATRIX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
